# Relucent Governance.
# (c) 2024 Relucent Ltd
# https://relucent.dev

# Note: this is a shared pipeline used by other repositories.
# Docs: https://docs.github.com/en/actions/using-workflows/reusing-workflows

name: Check Links

on:
  workflow_call:
    inputs:
      globs:
        type: string
        required: false
        description: "Globs to check for broken links"
        default: .

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2.0.2
        with:
          fail: true
          args:
            --no-progress ${{inputs.globs}} --exclude-path package.json
            --exclude-path node_modules
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
