# Relucent Governance.
# (c) 2024 Relucent Ltd
# https://relucent.dev

name: Check Scheduled

on:
  schedule:
    - cron: "30 8 * * 1"

jobs:
  check-links:
    uses: ./.github/workflows/check-links.yml
    secrets: inherit
