# Relucent Governance.
# (c) 2024 Relucent Ltd
# https://relucent.dev

name: Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm clean-install
      - run: npm run lint
